import React, { createContext, useState, useContext } from "react";

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState("en");

    const toggleLanguage = () => {
        setLanguage((prev) => (prev === "en" ? "am" : "en"));
    };

    const translations = {
        en: {
            welcome: "Welcome to EthioMeatApp",
            dashboard: "Dashboard",
            login: "Login",
            register: "Register",
            email: "Email",
            password: "Password",
            role: "Role",
            fullName: "Full Name",
            enterYourEmail: "Enter your email",
            enterYourPassword: "Enter your password",
            enterYourName: "Enter your name",
            createAccount: "Create Account",
            dontHaveAccount: "Don’t have an account?",
            alreadyHaveAccount: "Already have an account?",
            dashboardOverview: "Dashboard Overview",
            livestock: "Livestock",
            supplier: "Supplier",
            exporter: "Exporter",
            abattoir: "Abattoir",
            airline: "Airline",
            regulator: "Regulator",
            notifications: "Notifications",
            navigation: "Navigation",
            totalLivestock: "Total Livestock",
            availableForExport: "Available for Export",
            approvedExports: "Approved Exports",
            pendingApprovals: "Pending Approvals",
            app: "Ethio Meat Market",
            soldLivestock: "Sold Livestock",
            supplierDashboardTitle: "Supplier Dashboard",
            supplierDashboardDesc:
                "Manage livestock listings and register new animals for export.",
            exporterDashboardTitle: "Exporter Dashboard",
            exporterDashboardDesc:
                "Browse available livestock and manage export orders.",
            totalListings: "Total Livestock Listings",
            pendingOrders: "Pending Orders",
            approvedOrders: "Approved Orders",
            regulatorDashboardTitle: "Regulatory Authority Dashboard",
            regulatorDashboardDesc:
                "Monitor export activities, manage approvals, and review performance insights.",
            abattoirDashboardTitle: "Abattoir Dashboard",
            abattoirDashboardDesc:
                "Manage slaughter schedules, packaging, and airline coordination.",
            totalBatches: "Total Batches",
            scheduled: "Scheduled",
            inTransit: "In Transit",
            batchSchedules: "Batch Schedules",
            batchId: "Batch ID",
            abattoirLabel: "Abattoir",
            dateLabel: "Date",
            livestockBatch: "Livestock Batch",
            airlineLabel: "Airline",
            statusLabel: "Status",
            airlineDashboardTitle: "Airline Dashboard",
            airlineDashboardDesc:
                "Manage and track livestock cargo shipments across Ethiopia and abroad.",
            totalShipments: "Total Shipments",
            scheduledFlights: "Scheduled Flights",
            delivered: "Delivered",
            cargoShipmentsOverview: "Cargo Shipments Overview",
            flightId: "Flight ID",
            batchLabel: "Batch",
            departureDate: "Departure Date",
            availableLivestock: "Available Livestock",
            breedLabel: "Breed",
            weightLabel: "Weight",
            healthLabel: "Health",
            locationLabel: "Location",
            requestOrder: "Request Order",
            // Additional keys used by recently translated components
            notificationsTitle: "Notifications",
            typeLabel: "Type",
            monthlyExportVolumeTitle: "Monthly Export Volume (Dummy)",
            myOrders: "My Orders",
            orderId: "Order ID",
            quantity: "Quantity",
            status: "Status",
            date: "Date",
            approvedLabel: "Approved",
            pendingLabel: "Pending",
            pendingExportApprovals: "Pending Export Approvals",
            allOrdersApproved: "All orders have been approved.",
            action: "Action",
            approve: "Approve",
            orderApprovedAlert: "Order #{{id}} approved (dummy)",
            exportReports: "Export Performance Reports",
            exportReportsSummary:
                "Monthly export performance and livestock availability summary.",
            exportsLabel: "Exports",
            myLivestockListings: "My Livestock Listings",
            idLabel: "ID",
            breed: "Breed",
            weightKg: "Weight (kg)",
            health: "Health",
            location: "Location",
            availableLabel: "Available",
            soldLabel: "Sold",
            registerNewLivestock: "Register New Livestock",
            livestockRegistered: "Livestock registered successfully! (dummy)",
            type: "Type",
            typePlaceholder: "e.g., Cattle",
            breedPlaceholder: "e.g., Boran",
            weightPlaceholder: "e.g., 400",
            healthCondition: "Health Condition",
            healthPlaceholder: "e.g., Good",
            locationPlaceholder: "e.g., Adama",
            submit: "Submit",
            collapse: "Collapse",
            expand: "Expand",
        },
        am: {
            welcome: "እንኳን ደህና መጡ ወደ EthioMeatApp",
            dashboard: "ዳሽቦርድ",
            login: "መግቢያ",
            register: "ይመዝገቡ",
            email: "ኢሜይል",
            password: "የይለፍ ቃል",
            role: "ተገቢ ሚና",
            fullName: "ሙሉ ስም",
            enterYourEmail: "ኢሜይሎን አስገባ",
            enterYourPassword: "የይለፍ ቃልዎን ያስገቡ",
            enterYourName: "ስምዎን ያስገቡ",
            createAccount: "መለያ ፍጠር",
            dontHaveAccount: "ጓደኛ መለያ የለዎትም?",
            alreadyHaveAccount: "አስቀድሞ መለያ አሎዎ?",
            dashboardOverview: "ዳሽቦርድ እይታ",
            livestock: "እንስሳት",
            supplier: "አቅራቢ",
            exporter: "ኤክስፖርተር",
            abattoir: "እርድ ቤት",
            airline: "አየር መንገድ",
            regulator: "ቁጥጥር ባለስልጣን",
            notifications: "ማስታወቂያዎች",
            navigation: "አሰሳ",
            totalLivestock: "ጠቅላላ እንስሳት",
            availableForExport: "ለላክ የሚገኙ",
            approvedExports: "የተፈቀዱ ላክዎች",
            pendingApprovals: "የሚጠበቁ ፈቃዶች",
            app: "ኢትዮ ስጋ ገበያ",
            soldLivestock: "የተሸጡ እንስሳት",
            supplierDashboardTitle: "የአቅራቢ ዳሽቦርድ",
            supplierDashboardDesc: "የእንስሳት ዝርዝር ያስተካክሉ እና አዲስ እንስሳ ለላክ ይመዝግቡ።",
            exporterDashboardTitle: "የኤክስፖርተር ዳሽቦርድ",
            exporterDashboardDesc: "የሚገኙ እንስሳትን ያሳዩ እና የላክ ትዕዛዞችን ይቆጣጠሩ።",
            totalListings: "የእንስሳት ጠቅላላ ዝርዝር",
            pendingOrders: "የሚጠብቁ ትዕዛዞች",
            approvedOrders: "የተፈቀዱ ትዕዛዞች",
            regulatorDashboardTitle: "የቁጥጥር ባለስልጣን ዳሽቦርድ",
            regulatorDashboardDesc:
                "የላክ እንቅስቃሴዎችን ይከታተሉ፣ ፈቃዶችን ይንቁራሩ፣ እና የአፈጻጸም ግምገማዎችን ይያዙ።",
            abattoirDashboardTitle: "የአባቶይር ዳሽቦርድ",
            abattoirDashboardDesc:
                "የማስወገድ ሰሌዳዎችን፣ ጥቅልና የአየር መስርያ ቅድሚያዎችን ይንቁራሩ።",
            totalBatches: "ጠቅላላ ቡትች",
            scheduled: "የታቀደ",
            inTransit: "በመንቀሳቀስ ላይ",
            batchSchedules: "የቡትች እቅዶች",
            batchId: "የቡትች መታወቂያ",
            abattoirLabel: "አባቶይር",
            dateLabel: "ቀን",
            livestockBatch: "የእንስሳት ቡትች",
            airlineLabel: "አየር መንገድ",
            statusLabel: "ሁኔታ",
            airlineDashboardTitle: "የአየር መንገድ ዳሽቦርድ",
            airlineDashboardDesc: "የእንስሳት ከባድ ጭነቶችን በውስጥ እና ከውጭ ይከታተሉ።",
            totalShipments: "ጠቅላላ የጀብር ጭነቶች",
            scheduledFlights: "የታቀዱ ብረቶች",
            delivered: "ደርሷል",
            cargoShipmentsOverview: "የጭነት ጭነቶች እይታ",
            flightId: "የበረራ መታወቂያ",
            batchLabel: "ቡትች",
            departureDate: "የመነሻ ቀን",
            availableLivestock: "የሚገኙ እንስሳት",
            breedLabel: "የዘር",
            weightLabel: "ሚዛን",
            healthLabel: "ጤና",
            locationLabel: "የቦታ",
            requestOrder: "የማስያዣ ትዕዛዝ",
            // Additional Amharic keys used by recently translated components
            notificationsTitle: "ማስታወቂያዎች",
            typeLabel: "ዓይነት",
            monthlyExportVolumeTitle: "የወርሃዊ የላክ ዝርዝር (ዳሚ)",
            myOrders: "ትዕዛዞቼ",
            orderId: "የትዕዛዝ መታወቂያ",
            quantity: "ብዛት",
            status: "ሁኔታ",
            date: "ቀን",
            approvedLabel: "የተፈቀደ",
            pendingLabel: "የሚጠበቅ",
            pendingExportApprovals: "የሚጠበቁ የላክ ፈቃዶች",
            allOrdersApproved: "ሁሉም ትዕዛዞች ተፈቀዱ።",
            action: "ተግባር",
            approve: "ይፈቀዱ",
            orderApprovedAlert: "የትዕዛዝ #{{id}} ተፈቀዷል (ዳሚ)",
            exportReports: "የላክ የአፈጻጸም ሪፖርቶች",
            exportReportsSummary: "የወርሃዊ የላክ አፈጻጸም እና የእንስሳት የማስታወቂያ ማጠቃለያ።",
            exportsLabel: "ላክዎች",
            myLivestockListings: "የእኔ የእንስሳት ዝርዝሮች",
            idLabel: "መታወቂያ",
            breed: "ዘር",
            weightKg: "ሚዛን (ኪ.ግ)",
            health: "ጤና",
            location: "ቦታ",
            availableLabel: "አለ",
            soldLabel: "የተሸጠ",
            registerNewLivestock: "አዲስ እንስሳ ይመዝግቡ",
            livestockRegistered: "እንስሳ በትክክል ተመዝግቧል! (ዳሚ)",
            type: "አይነት",
            typePlaceholder: "ለምሳሌ፣ በሬ",
            breedPlaceholder: "ለምሳሌ፣ ቦራን",
            weightPlaceholder: "ለምሳሌ፣ 400",
            healthCondition: "የጤና ሁኔታ",
            healthPlaceholder: "ለምሳሌ፣ ጥሩ",
            locationPlaceholder: "ለምሳሌ፣ አዳማ",
            submit: "አስገባ",
            collapse: "ዝጋ",
            expand: "ክፈት",
        },
    };

    return (
        <LanguageContext.Provider
            value={{ language, toggleLanguage, translations }}
        >
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
